spring:
  datasource:
    url: jdbc:h2:mem:tripguide
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        max-page-size: 1000
        default-page-size: 8
        one-indexed-parameters: true

#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

api:
  frontend-ip-address: http://localhost:3000

jwt:
  secret: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef123456789abcdef123456789abcdef
  token-validate-second: 28800